name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: install

      - name: Release new version
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: npx semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
